---
title: "🗓️ Events"
excerpt: "Upcoming free events on embedded software, electronic design, FPGA, etc."
layout: page
published: true
modified_date: 2023-10-21
---

In this page, I was listing upcoming **free** events related to hardware design,
electronic design, embedded software, FPGA, etc. Now, this page is kept for
**historical purposes.** I left compiling events due to lack of interest.

## Some Past Events

| Date | Field | Event | Type | Organizer |
| ----- | ----- | ----- | ---- | --------- |
| 2023-09-20 | Hardware | [Fundamentals of Signal Integrity Tutorial: Don’t Be Confused by Ground](https://go.teledynelecroy.com/l/48392/2023-08-07/8nvtv3?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-20 | FPGA | [Maximize Design Productivity using Vivado ML with SystemVerilog](https://www.doulos.com/webinars/maximize-design-productivity-using-vivado-ml-with-systemverilog/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Doulos](https://www.doulos.com?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-20 | Digital Design, Verification | [Understanding Verification for Digital Design](https://us02web.zoom.us/webinar/register/3016945255647/WN_hGbOxp55Qki07fhJROO3Ag?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [BLT](https://bltinc.com?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-20 | Hardware | [Probing in Power Electronics – What to Use and Why Part 2: High Voltage Probe Real-world Examples and Comparisons](https://go.teledynelecroy.com/l/48392/2023-08-22/8nwryy?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-21 | Hardware | [Fundamentals of 10 Mb/s In-vehicle Networks Webinar](https://go.teledynelecroy.com/l/48392/2023-08-23/8nww78?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-21 | Hardware | [EMC / ESD Pulse Measurements using Oscilloscopes](https://go.teledynelecroy.com/l/48392/2023-08-23/8nww7n?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-21 | Embedded | [Using Remote Access to Identify and Solve Customer Issues in Field Devices](https://www.toradex.com/webinars/remote-access-identify-solve-field-devices-issues?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Toradex](https://www.toradex.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-22 | Software | [What is an SBOM and why should I care?](https://www.doulos.com/webinars/what-is-an-sbom/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Doulos](https://www.doulos.com?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-26 | Hardware | [DDR Technology How to Probe and Debug DDR Signals](https://go.teledynelecroy.com/l/48392/2023-09-07/8nxz7v?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-27 | Hardware | [How Can I Reduce Noise on Signals Measured With an Oscilloscope?](https://go.teledynelecroy.com/l/48392/2023-09-04/8nxmpc?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-27 | FPGA, Embedded | [Starting AI Engine Development with the Vitis Software Platform](https://webinar.amd.com/2023-Vitis-Developer-Series/en/registration?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [AMD](https://www.amd.com?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-27 | Management | [Outsourcing Design Solutions for Defense Primes](https://us02web.zoom.us/webinar/register/8016945257563/WN_X1g09p2bTYO7bVWj8G0aIQ?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [BLT](https://bltinc.com?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-28 29 | FPGA | [Maximizing the Potential of Versal AI Engines ONLINE WORKSHOP](https://www.doulos.com/training/fpga-and-hardware-design/xilinx/maximizing-the-potential-of-versal-ai-engines-online-workshop/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) ⭐ | Online Workshop, 8 hours | [Doulos](https://www.doulos.com?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-28 | Hardware | [How Do I Make a Differential Measurement on an Oscilloscope Using Passive Probes?](https://go.teledynelecroy.com/l/48392/2023-06-26/8ns28q?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-28 | FPGA, Embedded | [Multimedia Accelerators for Kria SOM with HLS & Vitis Libraries](https://plc2.com/training/multimedia-accelerators-for-kria-som-with-hls-vitis-libraries_we/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [PLC2](https://plc2.com?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-09-28 | FPGA | [Eliminating Memory Bottlenecks with Versal™ HBM Series - From Architecture to Implementation](https://pages.xilinx.com/EN-WB-2023-09-27-VersalHBM_LP-Registration.html?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [AMD](https://www.amd.com?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-10-03 | Linux, Embedded | [Demystifying the Linux Kernel Security Process](https://www.linuxfoundation.org/webinars/demystifying-the-linux-kernel-security-process?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [The Linux Foundation](https://www.linuxfoundation.org/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-10-04 | FPGA, Embedded| [Signal Processing on AI Engine Using Vitis DSP Libraries and Vitis Model Composer](https://webinar.amd.com/2023-Vitis-Developer-Series/en/registration?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [AMD](https://www.amd.com?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-10-04 | FPGA, Embedded | [AMD Day](https://empa.com/amd-day/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) ⭐ | Ankara, Türkiye 📍 | [Empa](https://empa.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-10-04 | Hardware | [Oscilloscopes Best Practice - Part 2 How to Improve the Use of your Oscilloscope](https://go.teledynelecroy.com/l/48392/2023-08-31/8nxgsv?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-10-04 | Hardware | [How to Debug PCIe® Link Equalization (LEQ) Training and Other Dynamic Link Behaviors](https://go.teledynelecroy.com/l/48392/2023-08-08/8nvxy6?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-10-05 | Hardware | [Jitter Basics - Part 1](https://go.teledynelecroy.com/l/48392/2023-08-29/8nx6yv?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-10-05 | Hardware | [Fundamentals of Power Integrity Tutorial: Measuring Power Sources](https://go.teledynelecroy.com/l/48392/2023-08-22/8nwrv2?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Teledyne LeCroy](https://www.teledynelecroy.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-10-25 | Embedded | [Modernizing Embedded Software Development Practices](https://www.beningo.com/webinars/webinar-registration/?webinarKey=3695052195634483800&utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Beningo Embedded Group](https://www.beningo.com/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
| 2023-10-27 | Embedded | [Modern C++ for Safe and Efficient Embedded Systems](https://www.doulos.com/webinars/modern-cplusplus-for-safe-and-efficient-embedded-systems/?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) | Webinar | [Doulos](https://www.doulos.com?utm_source=alperyazarcom&utm_medium=web&utm_campaign=events) |
